const { B, log, launch, signedIn, clearThrottle } = require('./lib.cjs');
const psql = (q) => require('child_process').execFileSync('/usr/lib/postgresql/16/bin/psql', ['-h', '127.0.0.1', '-p', '5544', '-U', 'dev', '-d', 'aaicbi_dev', '-At', '-c', q]).toString().trim();
(async () => {
  const br = await launch(); const errs = [];
  clearThrottle(); psql(`delete from "GuideUnanswered"; delete from "GuideEntry"; delete from "GuideDailyStat"`);
  const sa = await signedIn(br, { viewport: { width: 1366, height: 900 } }, '/api/auth/login', 'super@dev.test');
  // seed via the public path like real visitors
  const post = (q, extra = {}) => sa.request.post(B + '/api/guide/unanswered', { data: { question: q, reason: 'NO_MATCH', confidence: 0.12, route: '/employer/dashboard', page: 'Employer dashboard', ...extra } });
  for (const q of ['How do I invite another employer to my team?', 'How can I invite an employer to join my team?', 'Where do I invite employers to my team?']) await post(q);
  for (let i = 0; i < 6; i++) await post('How do I invite another employer to my team?');
  await post('How do I change my profile picture?', { route: '/trainee/settings', page: 'Settings' });
  await post('Where can I see my messages?', { route: '/trainee/dashboard', page: 'Dashboard', reason: 'LOW_CONFIDENCE', confidence: 0.4, attempted: 'where do i find my certificate' });
  clearThrottle();
  const p = await sa.newPage(); p.setDefaultTimeout(15000); p.on('pageerror', (e) => errs.push(e.message.slice(0, 90)));
  await p.goto(B + '/admin/command/guide', { waitUntil: 'load' }); await p.waitForTimeout(2000);
  log(await p.getByRole('heading', { name: 'Guide Bot Knowledge' }).isVisible(), 'page is titled Guide Bot Knowledge');
  const tabs = await p.getByRole('tab').allInnerTexts();
  log(['Overview', 'Frequently asked', 'Knowledge base', 'Navigation', 'Learning history', 'Categories', 'Settings'].every((t) => tabs.some((x) => x.startsWith(t))) && tabs.some((x) => x.startsWith('Needs review (')), 'tabs: ' + tabs.join(' | '));
  await p.screenshot({ path: '/tmp/guide-admin-overview.png' });
  await p.getByRole('tab', { name: /Needs review/ }).click(); await p.waitForTimeout(1200);
  const txt = await p.locator('main').innerText();
  log(/Asked 9 times/.test(txt) && /Also asked as/.test(txt) && /invite an employer to join/.test(txt), 'queue groups the three wordings into one topic asked 9 times');
  log(/High priority|Medium priority/.test(txt) && /Why it is here/.test(txt) && /employer\/dashboard/.test(txt) && /Confidence 12%/.test(txt), 'priority, reason, area and confidence are shown');
  log(/Closest answer Loop tried/.test(txt) && /where do i find my certificate/.test(txt), 'a low-confidence question shows the answer Loop tried');
  const firstRow = await p.locator('[role=tabpanel] ul > li').first().innerText();
  log(/invite another employer/i.test(firstRow), 'the most asked topic is listed first');
  await p.screenshot({ path: '/tmp/guide-admin-queue.png', fullPage: true });
  // approve through the UI
  await p.getByRole('button', { name: 'Write an answer' }).first().click(); await p.waitForTimeout(700);
  const dlg = p.getByRole('dialog');
  log(/Asked 9 times/.test(await dlg.innerText()) && (await dlg.getByLabel(/Other ways people ask this/).inputValue()).includes('invite an employer'), 'the answer form opens with the other wordings filled in');
  await dlg.getByLabel(/^Answer/).fill('Employers cannot add teammates yet. Contact the platform team and they will help.');
  await dlg.getByLabel(/^Category/).fill('Organizations and teams');
  await dlg.getByLabel(/^Page/).fill('/employer/settings'); await dlg.getByLabel('Button label').fill('Open Settings');
  await dlg.getByLabel('Control to light up').fill('nav:/employer/settings');
  await dlg.getByLabel('Employer').check();
  await p.screenshot({ path: '/tmp/guide-admin-form.png' });
  await dlg.getByRole('button', { name: 'Approve and publish' }).click(); await p.waitForTimeout(1500);
  log(await p.getByRole('dialog').count() === 0, 'approved and published');
  await p.getByRole('tab', { name: 'Knowledge base' }).click(); await p.waitForTimeout(800);
  log(/Version 1/.test(await p.locator('main').innerText()) && /Takes people to \/employer\/settings/.test(await p.locator('main').innerText()), 'it appears in the knowledge base as version 1, with its destination');
  await p.getByRole('button', { name: 'Edit' }).first().click(); await p.waitForTimeout(500);
  await p.getByRole('dialog').getByLabel(/^Answer/).fill('Employers cannot add teammates yet. Ask the platform team through Messages and we will help.');
  await p.getByRole('dialog').getByLabel(/What changed/).fill('Mention Messages');
  await p.getByRole('dialog').getByRole('button', { name: 'Save answer' }).click(); await p.waitForTimeout(1500);
  log(/Version 2/.test(await p.locator('main').innerText()), 'edit saved as version 2');
  await p.getByRole('button', { name: 'History' }).first().click(); await p.waitForTimeout(800);
  const h = await p.getByRole('dialog').innerText();
  log(/Version 2/.test(h) && /Version 1/.test(h) && /Mention Messages/.test(h) && /super|Super|Admin/i.test(h), 'history lists both versions, the note and who changed it');
  await p.screenshot({ path: '/tmp/guide-admin-history.png' });
  await p.getByRole('button', { name: 'Restore this version' }).click(); await p.waitForTimeout(400);
  await p.getByRole('button', { name: 'Restore', exact: true }).click(); await p.waitForTimeout(1500);
  await p.getByRole('tab', { name: 'Knowledge base' }).click();
  log(/Version 3/.test(await p.locator('main').innerText()) && /cannot add teammates yet\. Contact/.test(await p.locator('main').innerText()), 'restoring version 1 gives version 3 with the first text');
  await p.getByRole('tab', { name: 'Navigation' }).click(); await p.waitForTimeout(500);
  log(/employer\/settings/.test(await p.locator('main').innerText()), 'navigation tab lists answers that send people somewhere');
  await p.getByRole('tab', { name: 'Overview' }).click(); await p.waitForTimeout(500);
  log(/Where people are getting stuck/.test(await p.locator('main').innerText()) && /trainee\/settings|employer\/dashboard/.test(await p.locator('main').innerText()), 'overview shows where people get stuck');
  await p.getByRole('tab', { name: 'Learning history' }).click(); await p.waitForTimeout(800);
  log(/Changes to answers/.test(await p.locator('main').innerText()) && /Decisions on questions/.test(await p.locator('main').innerText()), 'learning history tab');
  await p.getByRole('tab', { name: 'Pointing targets' }).click(); await p.waitForTimeout(400);
  log(/create-course/.test(await p.locator('main').innerText()), 'pointing targets tab lists controls and menu ids');
  // keyboard
  await p.getByRole('tab', { name: 'Overview' }).click(); await p.getByRole('tab', { name: 'Overview' }).focus(); await p.keyboard.press('ArrowRight');
  log(await p.getByRole('tab', { name: /Needs review/ }).getAttribute('aria-selected') === 'true', 'arrow keys move between tabs');
  // phone
  const ph = await br.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true }); await ph.addCookies(await sa.cookies());
  const pp = await ph.newPage(); await pp.goto(B + '/admin/command/guide', { waitUntil: 'load' }); await pp.waitForTimeout(2000);
  log(await pp.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'admin guide has no sideways scroll on a phone');
  await pp.getByRole('tab', { name: /Needs review|Overview/ }).first().click();
  await pp.screenshot({ path: '/tmp/guide-admin-phone.png' });
  console.log('page errors:', errs.length ? errs : 'none');
  await br.close();
})().catch((e) => { console.log('FATAL', e.message.split('\n')[0]); process.exit(1); });
