import type { Playbook } from "@/lib/guide/playbooks/types";

/**
 * Step-by-step guides for training organizations, written from the real
 * screens. **Bold** marks an exact label in the interface; a test checks
 * each one against the source so a renamed button cannot quietly leave a
 * guide wrong. Nothing here states a price, a date or a limit that lives
 * on a page and changes.
 */
export const PLAYBOOKS: Playbook[] = [
  {
    id: "workspace-tour",
    title: "Tour of your workspace",
    question: "Show me around my organization workspace",
    summary: "Your workspace has a menu down the left side (a button at the top on a phone). Here is what each part is for.",
    keywords: ["tour", "menu", "sidebar", "navigation", "where is", "find", "pages", "layout", "around", "interface", "workspace", "overview"],
    steps: [
      { title: "Overview is your home", text: "After you sign in you land on **Overview**. It shows your active trainees, courses, certificates issued and completion, with a table of progress by course.", href: "/admin/organization", hrefLabel: "Open Overview" },
      { title: "Teaching", text: "Under **Teaching** you build and run the training: **Courses**, **Examinations**, **Assignments** and **Certificates**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Organization", text: "Under **Organization** you manage the team and how the world sees you: **Team**, **Public profile**, **Education videos**, **Program skills**, **Content and visibility** and **Events**.", href: "/admin/organization/profile", hrefLabel: "Open Public profile" },
      { title: "Insight and Money", text: "**Performance** shows how each trainee is doing in a course. **Payments** lists every payment attempt across your courses.", href: "/admin/performance", hrefLabel: "Open Performance" },
      { title: "Settings and help", text: "**Settings** holds your profile picture and the dark mode switch. On any page, ask me \"What can I do on this page?\" and I will explain it.", href: "/admin/settings", hrefLabel: "Open Settings" },
    ],
    next: ["upload-course", "public-profile", "invite-team"],
  },
  {
    id: "upload-course",
    title: "Upload and publish a course",
    question: "How do I upload a course?",
    summary: "A course is built in order: create it, add modules, add lessons, add materials, add an assessment, then publish. A new course starts as a draft, so nothing is public until you publish.",
    keywords: ["upload", "course", "create course", "publish", "add course", "new course", "program", "programme", "lesson", "module", "material", "post course", "put my course", "post my course"],
    steps: [
      { title: "Open Courses", text: "In the menu choose **Courses**, then press **+ Create Course**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Describe the course", text: "Fill in **Course Title** (at least 3 letters) and **Description**. Leave **This course is free (lifetime access, no payment)** ticked for a free course, or untick it to set the **Price (₦)** and how access works.", href: "/admin/courses/new", hrefLabel: "Open the create form", tip: "You can change the price later under Pricing & Access in the course." },
      { title: "Create it", text: "Press **Create & Add Modules**. You land on the course page, where the rest is done." },
      { title: "Add a module", text: "A module is a chapter. Scroll to the modules, press **+ Add Module**, give it a title and press **Add Module**. Repeat for each chapter.", tip: "Trainees go through modules in order, so add them in the order you want them taken. Use **Move module up** and **Move module down** to reorder." },
      { title: "Add a lesson", text: "Inside a module press **+ Add Lesson**, give it a title and press **Add Lesson**. A lesson is a titled container; its content is added as materials." },
      { title: "Add materials", text: "Inside a lesson press **+ Add Material**. Choose the type: **PDF**, **DOCX**, **PPTX** or **Video (YouTube link)**. Give it a **Material title**, then **Choose file** to upload or switch to **Paste a link**.", tip: "Files can be up to 20MB each. Videos are links only and must be YouTube or Google-hosted." },
      { title: "Add an assessment", text: "On a module press **Assessment** to give it a quiz trainees must pass before the next module opens. Ask me \"How do I set a module assessment?\" for those steps." },
      { title: "Pick your certificate", text: "In the course page open **Certificate Template** and choose one of your approved templates, or keep **AAICBI default**." },
      { title: "Check as a trainee", text: "Press **Preview as Trainee** to see exactly what trainees will see." },
      { title: "Publish", text: "Set **Status** to **Published**. A course needs at least one module to be published. Use **Copy Trainee Link** to share it.", tip: "**Unlisted** hides the course from the public catalog so only people you enroll can reach it. Use **Archived** or **Unpublished** instead of deleting a course that has trainees or certificates." },
    ],
    next: ["module-assessment", "final-exam", "course-details", "enroll-trainees"],
  },
  {
    id: "module-assessment",
    title: "Set a module assessment",
    question: "How do I set a module assessment?",
    summary: "A module assessment is a multiple-choice quiz made from a Word document you upload. Trainees must pass it to unlock the next module.",
    keywords: ["assessment", "quiz", "test", "questions", "question", "docx", "word document", "import", "multiple choice", "pass mark", "mcq", "exam"],
    steps: [
      { title: "Prepare the Word file", text: "Write multiple-choice questions in a Word (.docx or .doc) or PDF file. Number each question (1. or Question 1:), give options A to D, and add an answer line such as \"Answer: B\".", tip: "There is no screen for typing a question in by hand; questions come from the document, and you can edit them afterwards." },
      { title: "Open the assessment", text: "In the course page press **Assessment** on the module." },
      { title: "Upload the questions", text: "Press **Choose Word or PDF file**. The assessment is created and the questions are read in. You get an import summary showing how many are valid and how many need review.", tip: "The file can be up to 10MB." },
      { title: "Set the rules", text: "Open **Assessment Settings** and set **Duration (minutes)**, **Pass Mark (%)**, **Questions per attempt (blank = all)** and **Max attempts (blank = unlimited)**. Press **Save Settings**." },
      { title: "Review flagged questions", text: "Questions marked needs review must be fixed: press **Edit**, select the correct option and **Save**, or **Approve as-is**. Use **Delete** to remove one." },
      { title: "Publish", text: "Press **Publish Assessment**. It stays disabled while any question still needs review or there are no questions.", tip: "Until it is published nothing is locked for trainees." },
    ],
    next: ["final-exam", "upload-course"],
  },
  {
    id: "final-exam",
    title: "Create the final course examination",
    question: "How do I create a final course exam?",
    summary: "The course examination is built for you from your published module assessments, then you review and publish it. Trainees take it once every module is complete.",
    keywords: ["final exam", "course exam", "course examination", "final", "generate", "examination", "end of course"],
    steps: [
      { title: "Publish module assessments first", text: "Either let Loop build it from your published module assessments, or import your own questions. To generate, publish the module assessments first; to import, you can skip that." },
      { title: "Open Course Examination", text: "In the course page choose **Course Examination**, then press **Generate Course Examination** (or import your own file, next step).", tip: "Each click makes up to 20 questions. Press **Generate More** to continue." },
      { title: "Or import your own PDF or Word file", text: "Instead of generating, press **Import questions (PDF or Word)** and choose a file of numbered multiple-choice questions with options A to D and an answer line. Imported questions are flagged only when the answer is unclear.", tip: "A PDF must contain real text. A scanned photo of a page cannot be read; use a Word file instead." },
      { title: "Review every question", text: "Generated questions all need your review, and imported ones flagged for review do too. Approve, edit or reject each one." },
      { title: "Set the rules", text: "Open **Examination Settings** to set **Duration (minutes)**, **Pass Mark (%)** and **Retake cooldown (hours, blank = none)**, then **Save Settings**." },
      { title: "Publish", text: "Press **Publish**. It cannot be published while questions still need review.", href: "/admin/courses", hrefLabel: "Open Courses" },
    ],
    next: ["certificates"],
  },
  {
    id: "course-details",
    title: "Price, schedule and describe a course",
    question: "How do I set the price, schedule and details of a course?",
    summary: "Everything beyond the title is set on the course page after you create it.",
    keywords: ["price", "pricing", "free", "discount", "subscription", "schedule", "start date", "registration", "deadline", "flyer", "marketing", "details", "category", "level", "whatsapp", "preview", "curriculum", "reminder"],
    steps: [
      { title: "Price and access", text: "In **Pricing & Access** press **Edit**. Choose free or paid, the **Price (₦)**, an optional **Discount (%, optional)**, and **Recurring subscription** or **Fixed-duration access**. Use **Free preview modules (optional)** to let people try the first modules before paying.", tip: "Preview modules must be fewer than the course's total modules." },
      { title: "Schedule and registration", text: "In **Schedule & Registration** set **Start date**, **Registration deadline**, **Location** and optional **Capacity (optional)**, then **Save schedule & registration**. Leave it blank for an ordinary course with no launch date.", tip: "When a start date is set, people can only enroll while registration is open." },
      { title: "Describe it for visitors", text: "In **Course Information & Marketing Materials** fill in **Category**, **Level**, **Duration**, **Training format**, **Who this course is for** and the lists, then **Save course information**." },
      { title: "Flyer and curriculum", text: "Use **Upload flyer** (JPG, PNG or WEBP up to 8MB) and **Upload curriculum** (PDF or Word up to 10MB). The switches under **Visible on the public course page** choose what visitors see." },
      { title: "Keep trainees connected", text: "Add a **WhatsApp group link** trainees see after enrolling, and set **Early-Warning Thresholds** to flag trainees who go quiet." },
    ],
  },
  {
    id: "enroll-trainees",
    title: "Enroll trainees and make cohorts",
    question: "How do I add trainees to my course?",
    summary: "You can enroll a trainee yourself by their email, and group trainees who start together into a cohort.",
    keywords: ["enroll", "enrol", "add trainee", "add student", "cohort", "intake", "batch", "invite trainee", "access", "grant access"],
    steps: [
      { title: "Open the course", text: "Go to **Courses** and press **Manage** on the course.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Enrollments", text: "Choose **Enrollments**, type the trainee's email and press **Grant Access**. They get an email.", tip: "The trainee needs a trainee account first. If your plan has a seat limit you will be told when it is reached. Use **Revoke** or **Extend Access** later." },
      { title: "Make a cohort", text: "Choose **Cohorts / Intakes**, press **+ New Cohort**, fill in the name (for example January intake) and optional dates, and press **Create Cohort**. Open the cohort and use **Trainee email** with **Enroll** to add people.", tip: "A cohort is for reporting only; it does not give course access." },
      { title: "Follow progress", text: "**Early Warnings** flags trainees who stop logging in, and **Performance** shows each trainee's results.", href: "/admin/performance", hrefLabel: "Open Performance" },
    ],
    next: ["certificates"],
  },
  {
    id: "certificates",
    title: "Design and use certificates",
    question: "How do I design certificates with my logo?",
    summary: "You design a certificate template, send it to AAICBI for approval, then choose it on each course.",
    keywords: ["certificate", "template", "logo", "watermark", "signature", "signatory", "design", "branding", "remove watermark", "powered by"],
    steps: [
      { title: "Open Certificates", text: "In the menu choose **Certificates**.", href: "/admin/certificate-templates", hrefLabel: "Open Certificates" },
      { title: "Start a template", text: "Press **+ New** (or **Choose a starting template** to start from a design). Give it a name, add the signatory name and title, and use **Upload logo** for your logo." },
      { title: "Check it", text: "Use **Preview** to see exactly what is on the canvas. Your work saves as a draft automatically; **Save changes** saves now." },
      { title: "Send for review", text: "Press **Send for Review**. AAICBI approves templates before courses can use them; approved templates are locked.", tip: "Until yours is approved, courses use the AAICBI default certificate." },
      { title: "Use it on a course", text: "Open the course and pick the template under **Certificate Template**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "About the watermark", text: "Certificates carry a small \"Powered by AAICBI\" line. To remove it, see **Billing and plan** from your Overview page.", href: "/org/billing", hrefLabel: "Open Billing and plan" },
    ],
    next: ["upload-course"],
  },
  {
    id: "public-profile",
    title: "Set up your public page",
    question: "How do I set up my organization's public page?",
    summary: "Your public page is what visitors see in the ecosystem. It is off until you switch it on, and your organization must be approved first.",
    keywords: ["public profile", "public page", "profile", "tagline", "cover", "about", "slug", "page address", "visible", "show my organization", "listing"],
    steps: [
      { title: "Open Public profile", text: "In the menu under **Organization** choose **Public profile**.", href: "/admin/organization/profile", hrefLabel: "Open Public profile" },
      { title: "Fill the details", text: "Set your **Page address**, **Tagline**, **Location**, **Cover image URL** and **About**. Only these fields are ever shown publicly." },
      { title: "Switch it on", text: "Turn on **Show my organization page publicly**, then press **Save**.", tip: "It is off by default. A **Verified** badge is added by AAICBI; you cannot set it yourself." },
      { title: "See it", text: "Press **View page** to see what visitors see." },
    ],
    next: ["events", "education-videos"],
  },
  {
    id: "invite-team",
    title: "Invite a teammate",
    question: "How do I add a teammate to my organization?",
    summary: "Teammates sign in with their own email and password and can manage the same courses, trainees and certificates you can.",
    keywords: ["team", "teammate", "colleague", "staff", "invite", "add user", "co-admin", "instructor", "assistant"],
    steps: [
      { title: "Open Team", text: "In the menu under **Organization** choose **Team**.", href: "/admin/organization/team", hrefLabel: "Open Team" },
      { title: "Invite", text: "Under **Invite a teammate** enter their **Name** and **Email**, then press **Send invitation**." },
      { title: "If the email does not arrive", text: "Send them the **Invitation link** shown on the page with **Copy**.", tip: "The link works once and expires in 48 hours." },
      { title: "Manage them later", text: "In the **Teammates** table you can **Resend invitation**, **Disable**, **Enable** or **Remove** a person." },
    ],
  },
  {
    id: "education-videos",
    title: "Publish a trainee's video",
    question: "How do I publish a trainee education video?",
    summary: "You can share a YouTube video one of your trainees presented. The trainee is asked to agree before anything is shown publicly.",
    keywords: ["video", "education", "youtube", "trainee video", "presentation", "publish video", "post video", "learn"],
    steps: [
      { title: "Open Education videos", text: "In the menu under **Organization** choose **Education videos**.", href: "/admin/education", hrefLabel: "Open Education videos" },
      { title: "Pick the trainee", text: "Choose the **Trainee**. Only trainees enrolled in your programs are listed." },
      { title: "Add the video", text: "Paste the **YouTube link** and press **Check link**, then add a **Video title**, **Description**, the **Program** and the **Skills**." },
      { title: "Send it", text: "Press **Send for trainee consent**. It goes live after the trainee agrees (and after AAICBI review if your organization is not verified).", tip: "Track it under Your videos: Waiting for trainee, In review, Published." },
    ],
    next: ["program-skills"],
  },
  {
    id: "program-skills",
    title: "Tag your programs with skills",
    question: "How do I tag my courses with skills?",
    summary: "When a visitor watches a video about a skill, matching programs are suggested. Tagging your courses is how yours get suggested.",
    keywords: ["skills", "tag", "program skills", "suggest", "discover", "taught"],
    steps: [
      { title: "Open Program skills", text: "In the menu under **Organization** choose **Program skills**.", href: "/admin/organization/programs", hrefLabel: "Open Program skills" },
      { title: "Tag each program", text: "In **Skills taught** list the skills, separated by commas, then press **Save skills**." },
    ],
  },
  {
    id: "events",
    title: "Publish an event",
    question: "How do I post an event?",
    summary: "Events like open days and workshops appear on your public page and on the events page. Visitors register on your own link.",
    keywords: ["event", "open day", "workshop", "webinar", "demo day", "announce", "post event", "calendar"],
    steps: [
      { title: "Open Events", text: "In the menu under **Organization** choose **Events**.", href: "/admin/organization/events", hrefLabel: "Open Events" },
      { title: "Fill the form", text: "Enter the **Title** and when it **Starts (UTC)**. Add an end time, the place and a registration link if you want them." },
      { title: "Publish", text: "Press **Publish event**. Use **Remove** on an event to take it down.", tip: "Times are in UTC. Registration happens on your own link; nothing is collected here." },
    ],
  },
  {
    id: "insights",
    title: "Read your numbers",
    question: "How do I see how my content is doing?",
    summary: "Content and visibility shows who is finding you and what they do next, as anonymous counts.",
    keywords: ["insights", "views", "visits", "analytics", "statistics", "stats", "visibility", "followers", "rating"],
    steps: [
      { title: "Open Content and visibility", text: "In the menu under **Organization** choose **Content and visibility**.", href: "/admin/organization/insights", hrefLabel: "Open Content and visibility" },
      { title: "Read it", text: "You will see **Page visits**, **Video views**, **Program clicks**, **New followers** and **New enrollments**, your top videos, and tips under **Your visibility**.", tip: "Nobody is identified. Turn on your public page to be shown to visitors." },
    ],
  },
  {
    id: "payments-reports",
    title: "Payments and reports",
    question: "Where do I see payments and download reports?",
    summary: "Payments lists what trainees paid for your courses. Overview lets you download your data as spreadsheets.",
    keywords: ["payments", "money", "revenue", "report", "download", "csv", "spreadsheet", "export", "billing", "plan", "fee", "invoice"],
    steps: [
      { title: "Payments", text: "Choose **Payments** in the menu. Filter by **Success**, **Pending**, **Failed** or **Abandoned**.", href: "/admin/payments", hrefLabel: "Open Payments" },
      { title: "Reports", text: "On **Overview**, in the **Reports** card, download **Trainees and their progress**, **Completion by course** or **Cohort rosters** as CSV.", href: "/admin/organization", hrefLabel: "Open Overview" },
      { title: "Plan and billing", text: "**Billing and plan** shows your platform access and certificate branding.", href: "/org/billing", hrefLabel: "Open Billing and plan" },
    ],
  },
];
