import type { Playbook } from "@/lib/guide/playbooks/types";

/**
 * Step-by-step guides for training organizations, written from the real
 * screens. **Bold** marks an exact label in the interface; a test checks
 * each one against the source so a renamed button cannot quietly leave a
 * guide wrong. Nothing here states a price, a date or a limit that lives
 * on a page and changes.
 */
export const PLAYBOOKS: Playbook[] = [
  {
    id: "workspace-tour",
    audience: "organization",
    title: "Tour of your workspace",
    question: "Show me around my organization workspace",
    summary: "Your workspace has a menu down the left side (a button at the top on a phone). Here is what each part is for.",
    keywords: ["tour", "menu", "sidebar", "navigation", "where is", "find", "pages", "layout", "around", "interface", "workspace", "overview"],
    steps: [
      { title: "Overview is your home", text: "After you sign in you land on **Overview**. It shows your active trainees, courses, certificates issued and completion, with a table of progress by course.", href: "/admin/organization", hrefLabel: "Open Overview" },
      { title: "Teaching", text: "Under **Teaching** you build and run the training: **Courses**, **Examinations**, **Assignments** and **Certificates**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Organization", text: "Under **Organization** you manage the team and how the world sees you: **Team**, **Public profile**, **Education videos**, **Program skills**, **Content and visibility** and **Events**.", href: "/admin/organization/profile", hrefLabel: "Open Public profile" },
      { title: "Insight and Money", text: "**Performance** shows how each trainee is doing in a course. **Payments** lists every payment attempt across your courses.", href: "/admin/performance", hrefLabel: "Open Performance" },
      { title: "Settings and help", text: "**Settings** holds your profile picture and the dark mode switch. On any page, ask me \"What can I do on this page?\" and I will explain it.", href: "/admin/settings", hrefLabel: "Open Settings" },
    ],
    next: ["upload-course", "public-profile", "invite-team"],
  },
  {
    id: "upload-course",
    audience: "organization",
    title: "Upload and publish a course",
    question: "How do I upload a course?",
    summary: "A course is built in order: create it, add modules, add lessons, add materials, add an assessment, then publish. A new course starts as a draft, so nothing is public until you publish.",
    keywords: ["upload", "course", "create course", "publish", "add course", "new course", "program", "programme", "lesson", "module", "material", "post course", "put my course", "post my course"],
    steps: [
      { title: "Open Courses", text: "In the menu choose **Courses**, then press **+ Create Course**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Describe the course", text: "Fill in **Course Title** (at least 3 letters) and **Description**. Leave **This course is free (lifetime access, no payment)** ticked for a free course, or untick it to set the **Price (₦)** and how access works.", href: "/admin/courses/new", hrefLabel: "Open the create form", tip: "You can change the price later under Pricing & Access in the course." },
      { title: "Create it", text: "Press **Create & Add Modules**. You land on the course page, where the rest is done." },
      { title: "Add a module", text: "A module is a chapter. Scroll to the modules, press **+ Add Module**, give it a title and press **Add Module**. Repeat for each chapter.", tip: "Trainees go through modules in order, so add them in the order you want them taken. Use **Move module up** and **Move module down** to reorder." },
      { title: "Add a lesson", text: "Inside a module press **+ Add Lesson**, give it a title and press **Add Lesson**. A lesson is a titled container; its content is added as materials." },
      { title: "Add materials", text: "Inside a lesson press **+ Add Material**. Choose the type: **PDF**, **DOCX**, **PPTX** or **Video (YouTube link)**. Give it a **Material title**, then **Choose file** to upload or switch to **Paste a link**.", tip: "Files can be up to 20MB each. Videos are links only and must be YouTube or Google-hosted." },
      { title: "Add an assessment", text: "On a module press **Assessment** to give it a quiz trainees must pass before the next module opens. Ask me \"How do I set a module assessment?\" for those steps." },
      { title: "Pick your certificate", text: "In the course page open **Certificate Template** and choose one of your approved templates, or keep **AAICBI default**." },
      { title: "Check as a trainee", text: "Press **Preview as Trainee** to see exactly what trainees will see." },
      { title: "Publish", text: "Set **Status** to **Published**. A course needs at least one module to be published. Use **Copy Trainee Link** to share it.", tip: "**Unlisted** hides the course from the public catalog so only people you enroll can reach it. Use **Archived** or **Unpublished** instead of deleting a course that has trainees or certificates." },
    ],
    next: ["module-assessment", "final-exam", "course-details", "enroll-trainees"],
  },
  {
    id: "module-assessment",
    audience: "organization",
    title: "Set a module assessment",
    question: "How do I set a module assessment?",
    summary: "A module assessment is a multiple-choice quiz made from a Word document you upload. Trainees must pass it to unlock the next module.",
    keywords: ["assessment", "quiz", "test", "questions", "question", "docx", "word document", "import", "multiple choice", "pass mark", "mcq", "exam"],
    steps: [
      { title: "Prepare the Word file", text: "Write multiple-choice questions in a Word (.docx or .doc) or PDF file. Number each question (1. or Question 1:), give options A to D, and add an answer line such as \"Answer: B\".", tip: "There is no screen for typing a question in by hand; questions come from the document, and you can edit them afterwards." },
      { title: "Open the assessment", text: "In the course page press **Assessment** on the module." },
      { title: "Upload the questions", text: "Press **Choose Word or PDF file**. The assessment is created and the questions are read in. You get an import summary showing how many are valid and how many need review.", tip: "The file can be up to 10MB." },
      { title: "Set the rules", text: "Open **Assessment Settings** and set **Duration (minutes)**, **Pass Mark (%)**, **Questions per attempt (blank = all)** and **Max attempts (blank = unlimited)**. Press **Save Settings**." },
      { title: "Review flagged questions", text: "Questions marked needs review must be fixed: press **Edit**, select the correct option and **Save**, or **Approve as-is**. Use **Delete** to remove one." },
      { title: "Publish", text: "Press **Publish Assessment**. It stays disabled while any question still needs review or there are no questions.", tip: "Until it is published nothing is locked for trainees." },
    ],
    next: ["final-exam", "upload-course"],
  },
  {
    id: "final-exam",
    audience: "organization",
    title: "Create the final course examination",
    question: "How do I create a final course exam?",
    summary: "The course examination is built for you from your published module assessments, then you review and publish it. Trainees take it once every module is complete.",
    keywords: ["final exam", "course exam", "course examination", "final", "generate", "examination", "end of course"],
    steps: [
      { title: "Publish module assessments first", text: "Either let Loop build it from your published module assessments, or import your own questions. To generate, publish the module assessments first; to import, you can skip that." },
      { title: "Open Course Examination", text: "In the course page choose **Course Examination**, then press **Generate Course Examination** (or import your own file, next step).", tip: "Each click makes up to 20 questions. Press **Generate More** to continue." },
      { title: "Or import your own PDF or Word file", text: "Instead of generating, press **Import questions (PDF or Word)** and choose a file of numbered multiple-choice questions with options A to D and an answer line. Imported questions are flagged only when the answer is unclear.", tip: "A PDF must contain real text. A scanned photo of a page cannot be read; use a Word file instead." },
      { title: "Review every question", text: "Generated questions all need your review, and imported ones flagged for review do too. Approve, edit or reject each one." },
      { title: "Set the rules", text: "Open **Examination Settings** to set **Duration (minutes)**, **Pass Mark (%)** and **Retake cooldown (hours, blank = none)**, then **Save Settings**." },
      { title: "Publish", text: "Press **Publish**. It cannot be published while questions still need review.", href: "/admin/courses", hrefLabel: "Open Courses" },
    ],
    next: ["certificates"],
  },
  {
    id: "course-details",
    audience: "organization",
    title: "Price, schedule and describe a course",
    question: "How do I set the price, schedule and details of a course?",
    summary: "Everything beyond the title is set on the course page after you create it.",
    keywords: ["price", "pricing", "free", "discount", "subscription", "schedule", "start date", "registration", "deadline", "flyer", "marketing", "details", "category", "level", "whatsapp", "preview", "curriculum", "reminder"],
    steps: [
      { title: "Price and access", text: "In **Pricing & Access** press **Edit**. Choose free or paid, the **Price (₦)**, an optional **Discount (%, optional)**, and **Recurring subscription** or **Fixed-duration access**. Use **Free preview modules (optional)** to let people try the first modules before paying.", tip: "Preview modules must be fewer than the course's total modules." },
      { title: "Schedule and registration", text: "In **Schedule & Registration** set **Start date**, **Registration deadline**, **Location** and optional **Capacity (optional)**, then **Save schedule & registration**. Leave it blank for an ordinary course with no launch date.", tip: "When a start date is set, people can only enroll while registration is open." },
      { title: "Describe it for visitors", text: "In **Course Information & Marketing Materials** fill in **Category**, **Level**, **Duration**, **Training format**, **Who this course is for** and the lists, then **Save course information**." },
      { title: "Flyer and curriculum", text: "Use **Upload flyer** (JPG, PNG or WEBP up to 8MB) and **Upload curriculum** (PDF or Word up to 10MB). The switches under **Visible on the public course page** choose what visitors see." },
      { title: "Keep trainees connected", text: "Add a **WhatsApp group link** trainees see after enrolling, and set **Early-Warning Thresholds** to flag trainees who go quiet." },
    ],
  },
  {
    id: "message-trainees",
    audience: "organization",
    title: "Message your trainees",
    question: "How do I message my trainees?",
    summary: "You can chat with the trainees in your cohorts, one to one or in each cohort's group chat. You only see your own cohorts and your own conversations.",
    keywords: ["message", "messages", "chat", "talk to trainees", "contact trainees", "announce", "group chat", "cohort chat", "dm", "communicate", "reply"],
    steps: [
      { title: "Open Messages", text: "In the menu choose **Messages**. On a phone it is on the bottom bar.", href: "/admin/messages", hrefLabel: "Open Messages" },
      { title: "Find a conversation", text: "Your cohorts' group chats are listed for you. Use the search box to find a person or a message; unread conversations come first." },
      { title: "Start a chat", text: "Press **New chat** and choose a trainee from one of your cohorts.", tip: "Trainees appear here once they are in one of your cohorts. Add them under Cohorts / Intakes on a course." },
      { title: "Write and send", text: "Type in the box and press **Send**. The trainee gets a notification that says you wrote, never the message itself." },
      { title: "If someone misbehaves", text: "Open the menu at the top of a conversation to **Block** the person, or press **Report** under a message." },
    ],
    next: ["enroll-trainees"],
  },
  {
    id: "enroll-trainees",
    audience: "organization",
    title: "Enroll trainees and make cohorts",
    question: "How do I add trainees to my course?",
    summary: "You can enroll a trainee yourself by their email, and group trainees who start together into a cohort.",
    keywords: ["enroll", "enrol", "add trainee", "add student", "cohort", "intake", "batch", "invite trainee", "access", "grant access"],
    steps: [
      { title: "Open the course", text: "Go to **Courses** and press **Manage** on the course.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "Enrollments", text: "Choose **Enrollments**, type the trainee's email and press **Grant Access**. They get an email.", tip: "The trainee needs a trainee account first. If your plan has a seat limit you will be told when it is reached. Use **Revoke** or **Extend Access** later." },
      { title: "Make a cohort", text: "Choose **Cohorts / Intakes**, press **+ New Cohort**, fill in the name (for example January intake) and optional dates, and press **Create Cohort**. Open the cohort and use **Trainee email** with **Enroll** to add people.", tip: "A cohort is for reporting only; it does not give course access." },
      { title: "Follow progress", text: "**Early Warnings** flags trainees who stop logging in, and **Performance** shows each trainee's results.", href: "/admin/performance", hrefLabel: "Open Performance" },
    ],
    next: ["certificates"],
  },
  {
    id: "certificates",
    audience: "organization",
    title: "Design and use certificates",
    question: "How do I design certificates with my logo?",
    summary: "You design a certificate template, send it to AAICBI for approval, then choose it on each course.",
    keywords: ["certificate", "template", "logo", "watermark", "signature", "signatory", "design", "branding", "remove watermark", "powered by"],
    steps: [
      { title: "Open Certificates", text: "In the menu choose **Certificates**.", href: "/admin/certificate-templates", hrefLabel: "Open Certificates" },
      { title: "Start a template", text: "Press **+ New** (or **Choose a starting template** to start from a design). Give it a name, add the signatory name and title, and use **Upload logo** for your logo." },
      { title: "Or upload your own design", text: "If you already have a finished certificate design, press **Upload template** and choose a PNG, JPG or WEBP picture of it. It becomes the page, and the trainee name, course, date and code fields are placed on it for you to drag into position. **Replace template image** swaps it later and **Remove template image** goes back to a plain page.", tip: "Leave the spaces for the name, course and date empty in your picture, because those are filled in for each trainee. Images can be up to 10MB." },
      { title: "Check it", text: "Use **Preview** to see exactly what is on the canvas. Your work saves as a draft automatically; **Save changes** saves now." },
      { title: "Send for review", text: "Press **Send for Review**. AAICBI approves templates before courses can use them; approved templates are locked.", tip: "Until yours is approved, courses use the AAICBI default certificate." },
      { title: "Use it on a course", text: "Open the course and pick the template under **Certificate Template**.", href: "/admin/courses", hrefLabel: "Open Courses" },
      { title: "About the watermark", text: "Certificates carry a small \"Powered by AAICBI\" line. To remove it, see **Billing and plan** from your Overview page.", href: "/org/billing", hrefLabel: "Open Billing and plan" },
    ],
    next: ["upload-course"],
  },
  {
    id: "public-profile",
    audience: "organization",
    title: "Set up your public page",
    question: "How do I set up my organization's public page?",
    summary: "Your public page is what visitors see in the ecosystem. It is off until you switch it on, and your organization must be approved first.",
    keywords: ["public profile", "public page", "profile", "tagline", "cover", "about", "slug", "page address", "visible", "show my organization", "listing"],
    steps: [
      { title: "Open Public profile", text: "In the menu under **Organization** choose **Public profile**.", href: "/admin/organization/profile", hrefLabel: "Open Public profile" },
      { title: "Fill the details", text: "Set your **Page address**, **Tagline**, **Location**, **Cover image URL** and **About**. Only these fields are ever shown publicly." },
      { title: "Switch it on", text: "Turn on **Show my organization page publicly**, then press **Save**.", tip: "It is off by default. A **Verified** badge is added by AAICBI; you cannot set it yourself." },
      { title: "See it", text: "Press **View page** to see what visitors see." },
    ],
    next: ["events", "education-videos"],
  },
  {
    id: "invite-team",
    audience: "organization",
    title: "Invite a teammate",
    question: "How do I add a teammate to my organization?",
    summary: "Teammates sign in with their own email and password and can manage the same courses, trainees and certificates you can.",
    keywords: ["team", "teammate", "colleague", "staff", "invite", "add user", "co-admin", "instructor", "assistant"],
    steps: [
      { title: "Open Team", text: "In the menu under **Organization** choose **Team**.", href: "/admin/organization/team", hrefLabel: "Open Team" },
      { title: "Invite", text: "Under **Invite a teammate** enter their **Name** and **Email**, then press **Send invitation**." },
      { title: "If the email does not arrive", text: "Send them the **Invitation link** shown on the page with **Copy**.", tip: "The link works once and expires in 48 hours." },
      { title: "Manage them later", text: "In the **Teammates** table you can **Resend invitation**, **Disable**, **Enable** or **Remove** a person." },
    ],
  },
  {
    id: "education-videos",
    audience: "organization",
    title: "Publish a trainee's video",
    question: "How do I publish a trainee education video?",
    summary: "You can share a YouTube video one of your trainees presented. The trainee is asked to agree before anything is shown publicly.",
    keywords: ["video", "education", "youtube", "trainee video", "presentation", "publish video", "post video", "learn"],
    steps: [
      { title: "Open Education videos", text: "In the menu under **Organization** choose **Education videos**.", href: "/admin/education", hrefLabel: "Open Education videos" },
      { title: "Pick the trainee", text: "Choose the **Trainee**. Only trainees enrolled in your programs are listed." },
      { title: "Add the video", text: "Paste the **YouTube link** and press **Check link**, then add a **Video title**, **Description**, the **Program** and the **Skills**." },
      { title: "Videos trainees send you", text: "Trainees can also post videos to you themselves. They appear under **Videos trainees sent you**. Watch one on YouTube, then press **Approve**, or write a short reason and press **Decline**.", tip: "If your organization is not verified, an approved video still goes to AAICBI for a final check. A trainee whose video you decline can send it to AAICBI." },
      { title: "Send it", text: "Press **Send for trainee consent**. It goes live after the trainee agrees (and after AAICBI review if your organization is not verified).", tip: "Track it under Your videos: Waiting for trainee, In review, Published." },
    ],
    next: ["program-skills"],
  },
  {
    id: "program-skills",
    audience: "organization",
    title: "Tag your programs with skills",
    question: "How do I tag my courses with skills?",
    summary: "When a visitor watches a video about a skill, matching programs are suggested. Tagging your courses is how yours get suggested.",
    keywords: ["skills", "tag", "program skills", "suggest", "discover", "taught"],
    steps: [
      { title: "Open Program skills", text: "In the menu under **Organization** choose **Program skills**.", href: "/admin/organization/programs", hrefLabel: "Open Program skills" },
      { title: "Tag each program", text: "In **Skills taught** list the skills, separated by commas, then press **Save skills**." },
    ],
  },
  {
    id: "events",
    audience: "organization",
    title: "Publish an event",
    question: "How do I post an event?",
    summary: "Events like open days and workshops appear on your public page and on the events page. Visitors register on your own link.",
    keywords: ["event", "open day", "workshop", "webinar", "demo day", "announce", "post event", "calendar"],
    steps: [
      { title: "Open Events", text: "In the menu under **Organization** choose **Events**.", href: "/admin/organization/events", hrefLabel: "Open Events" },
      { title: "Fill the form", text: "Enter the **Title** and when it **Starts (UTC)**. Add an end time, the place and a registration link if you want them." },
      { title: "Publish", text: "Press **Publish event**. Use **Remove** on an event to take it down.", tip: "Times are in UTC. Registration happens on your own link; nothing is collected here." },
    ],
  },
  {
    id: "insights",
    audience: "organization",
    title: "Read your numbers",
    question: "How do I see how my content is doing?",
    summary: "Content and visibility shows who is finding you and what they do next, as anonymous counts.",
    keywords: ["insights", "views", "visits", "analytics", "statistics", "stats", "visibility", "followers", "rating"],
    steps: [
      { title: "Open Content and visibility", text: "In the menu under **Organization** choose **Content and visibility**.", href: "/admin/organization/insights", hrefLabel: "Open Content and visibility" },
      { title: "Read it", text: "You will see **Page visits**, **Video views**, **Program clicks**, **New followers** and **New enrollments**, your top videos, and tips under **Your visibility**.", tip: "Nobody is identified. Turn on your public page to be shown to visitors." },
    ],
  },
  {
    id: "payments-reports",
    audience: "organization",
    title: "Payments and reports",
    question: "Where do I see payments and download reports?",
    summary: "Payments lists what trainees paid for your courses. Overview lets you download your data as spreadsheets.",
    keywords: ["payments", "money", "revenue", "report", "download", "csv", "spreadsheet", "export", "billing", "plan", "fee", "invoice"],
    steps: [
      { title: "Payments", text: "Choose **Payments** in the menu. Filter by **Success**, **Pending**, **Failed** or **Abandoned**.", href: "/admin/payments", hrefLabel: "Open Payments" },
      { title: "Reports", text: "On **Overview**, in the **Reports** card, download **Trainees and their progress**, **Completion by course** or **Cohort rosters** as CSV.", href: "/admin/organization", hrefLabel: "Open Overview" },
      { title: "Plan and billing", text: "**Billing and plan** shows your platform access and certificate branding.", href: "/org/billing", hrefLabel: "Open Billing and plan" },
    ],
  },
  {
    id: "trainee-tour",
    audience: "trainee",
    title: "Tour of your trainee area",
    question: "Show me around my trainee dashboard",
    summary: "Everything you need is in the menu down the left side (the menu button on a phone). Here is what each part is for.",
    keywords: ["tour", "dashboard", "menu", "sidebar", "around", "where is", "find", "pages", "navigation", "interface", "my area"],
    steps: [
      { title: "Dashboard", text: "**Dashboard** is your home. **Continue Learning** shows your next step and a **Resume** button, and **Quick Actions** has shortcuts. Press **Show more** for the rest.", href: "/trainee/dashboard", hrefLabel: "Open Dashboard" },
      { title: "Courses", text: "**Courses** lists the programs you can join, and your own course pages are where lessons, assessments and your certificate live.", href: "/trainee/courses", hrefLabel: "Open Courses" },
      { title: "Examinations and Assignments", text: "**Examinations** lists every module assessment and course examination you can take. **Assignments** is for written work you save as you go and submit.", href: "/trainee/examinations", hrefLabel: "Open Examinations" },
      { title: "Certificates and progress", text: "**Certificates** holds what you have earned. **My Progress** shows your strengths and what to focus on next. **Analytics & Reports** lets you download a PDF report.", href: "/trainee/certificates", hrefLabel: "Open Certificates" },
      { title: "Messages and downloads", text: "**Messages** is for chatting with your cohort or staff. **My Downloads** lists materials you saved for offline reading.", href: "/trainee/messages", hrefLabel: "Open Messages" },
      { title: "Settings and help", text: "**Settings** holds notifications, language, **Low-bandwidth mode** and dark mode. On any page you can press **Page Help** at the bottom of the menu, or ask me \"What can I do on this page?\".", href: "/trainee/settings", hrefLabel: "Open Settings" },
    ],
    next: ["trainee-start", "trainee-enroll", "trainee-profile"],
  },
  {
    id: "trainee-start",
    audience: "trainee",
    title: "Get started as a trainee",
    question: "How do I get started as a trainee?",
    summary: "Four short steps: create your account, confirm your email, sign in, then join a course.",
    keywords: ["get started", "start learning", "begin", "first steps", "new trainee", "onboarding", "how to use", "register", "sign up", "verify email"],
    steps: [
      { title: "Create your account", text: "Open the registration page and fill in **Full name**, **Email** and **Password** (at least 8 characters). Tick the Privacy Policy box, then press **Create account**.", href: "/trainee/register", hrefLabel: "Open registration", tip: "You can also use **Sign up with Google**, after ticking the Privacy Policy box." },
      { title: "Confirm your email", text: "Open the email we send and press the link. You will see **Email Verified**, then press **Sign In**.", tip: "Nothing in your inbox? Check spam. Until you verify, your dashboard shows a reminder." },
      { title: "Sign in", text: "Enter your **Email** and **Password** and press **Sign in**. You land on your dashboard.", href: "/trainee/login", hrefLabel: "Open sign in", tip: "Forgot your password? Press **Forgot your password?** on the sign-in page." },
      { title: "Join a course", text: "On the **Courses** page pick a program and enroll. I can walk you through that next.", href: "/courses", hrefLabel: "Browse courses" },
    ],
    next: ["trainee-enroll", "trainee-tour"],
  },
  {
    id: "trainee-enroll",
    audience: "trainee",
    title: "Enroll in a course",
    question: "How do I enroll in a course?",
    summary: "Free courses open straight away. Paid courses are paid for securely online, and some let you try the first modules free.",
    keywords: ["enroll", "enrol", "join course", "join a course", "register for course", "pay", "payment", "paystack", "free preview", "unlock", "unlock code", "buy course", "renew"],
    steps: [
      { title: "Find the course", text: "Use **Search courses…** on the courses page, or browse **Available Courses**. Open one to read its overview (tap **Read more** for the full text), **What you'll learn** and **Course outline**.", href: "/courses", hrefLabel: "Browse courses" },
      { title: "Sign in to enroll", text: "If you are not signed in you will see **Log in to Enroll**. Sign in, or create an account first.", tip: "If registration is closed or has not opened you will see a message instead of a button." },
      { title: "Free course", text: "Press **Enroll**. The course opens straight away." },
      { title: "Paid course", text: "Press **Pay & Enroll** and complete the payment in the popup. You will get an email with a 6-digit code and an **Unlock the Course** button. Open it, enter the code and press **Unlock**.", tip: "The code expires after 15 minutes. If your payment seems stuck, use **Recheck my payment**." },
      { title: "Try before paying", text: "If the course offers it, press **Start Free Preview** to try the first modules free. When the preview ends, press **Pay Now** on the locked module to continue." },
      { title: "Keep your access", text: "If your access runs out you will see **Your course access has expired.** Press **Renew Access** to carry on with your progress." },
    ],
    next: ["trainee-learn"],
  },
  {
    id: "trainee-learn",
    audience: "trainee",
    title: "Learn through a course",
    question: "How do I take lessons and unlock the next module?",
    summary: "A course is a set of modules taken in order. You open lessons and materials, mark lessons complete, and pass the module assessment to unlock the next module.",
    keywords: ["lesson", "lessons", "module", "modules", "materials", "mark complete", "locked", "progress", "next module", "unlock module", "download", "offline", "video", "study", "learn"],
    steps: [
      { title: "Open your course", text: "Go to **Courses** and open your course. You will see your progress, for example how many modules are complete.", href: "/trainee/courses", hrefLabel: "Open Courses" },
      { title: "Open a module", text: "Press a module such as **Module 1** to open it and see its lessons.", tip: "A **Locked** badge means finish the previous module first." },
      { title: "Read and watch", text: "Open each lesson's materials. Videos load when you tap them. For files, use **Download for offline** to keep a copy; they are listed in **My Downloads**." },
      { title: "Mark lessons complete", text: "Press **Mark Complete** on each lesson when you are done. It changes to **Completed**, and you can press it again to undo.", tip: "If a module has no assessment, finishing every lesson completes it." },
      { title: "Take the assessment", text: "If the module has an assessment, press **Take Assessment**. Passing it completes the module and unlocks the next one. Ask me \"How do I take a module assessment?\" for the steps." },
      { title: "Ask a question", text: "Use **Q&A** on a lesson to ask your instructor or read earlier questions." },
    ],
    next: ["trainee-assessment", "trainee-exam"],
  },
  {
    id: "trainee-assessment",
    audience: "trainee",
    title: "Take a module assessment",
    question: "How do I take a module assessment?",
    summary: "A module assessment is timed. Read the rules first, because the clock starts when you press Start.",
    keywords: ["assessment", "quiz", "test", "take assessment", "retake", "attempts", "timer", "pass mark", "submit assessment", "module test"],
    steps: [
      { title: "Open it", text: "In your course, open the module and press **Take Assessment** (or **Retake Assessment**).", href: "/trainee/courses", hrefLabel: "Open Courses" },
      { title: "Read the rules", text: "The page shows how many questions, how long you have, the pass mark and how many attempts you have used. Tick **I have read the instructions**.", tip: "If you see \"You have used all N of your allowed attempts\" you cannot try again." },
      { title: "Start", text: "Press **Start Assessment**. The timer starts now, so do not refresh or close the browser." },
      { title: "Answer", text: "Pick one option per question. Use **Next** and **Previous**, and **Mark for review** for ones you want to look at again." },
      { title: "Submit", text: "On the last question press **Review & Submit**, check how many you have answered, then press **Submit**. It also submits by itself when time runs out." },
      { title: "See your result", text: "You will see **Passed** or **Not yet — try again**, your score and how you did by topic. Press **Back to Course** to continue." },
    ],
    next: ["trainee-exam"],
  },
  {
    id: "trainee-exam",
    audience: "trainee",
    title: "Take the course examination and earn your certificate",
    question: "How do I take the course examination and earn a certificate?",
    summary: "The course examination opens when every module is complete. Passing it earns your certificate.",
    keywords: ["course examination", "final exam", "exam", "examination", "certificate", "earn certificate", "name on certificate", "cooldown", "retake exam", "exam code", "enter code"],
    steps: [
      { title: "Complete every module", text: "On your course page you will see **Course Examination — complete every module first** until all modules are done. Then it becomes **Course Examination available**.", href: "/trainee/courses", hrefLabel: "Open Courses" },
      { title: "Start it", text: "Press **Start** (or open **Examinations** and press **Start**).", href: "/trainee/examinations", hrefLabel: "Open Examinations" },
      { title: "Check your name", text: "In **Name on your certificate** type your name exactly as it should be printed. This is the name that appears on your certificate." },
      { title: "Begin", text: "Tick **I have read the instructions** and press **Start Examination**. The timer starts now.", tip: "After a failed attempt you may have to wait before you can retake. The page shows when it is available again." },
      { title: "Submit and see your result", text: "Answer, then press **Review & Submit** and **Submit**. The result page shows whether you passed." },
      { title: "Get your certificate", text: "Passing issues your certificate. Find it under **Certificates**, then press **View & verify**.", href: "/trainee/certificates", hrefLabel: "Open Certificates" },
      { title: "Have an exam code?", text: "If your instructor gave you a code for a separate exam, open the code page, type it under **Enter your examination code** and press **Continue**.", href: "/exam/enter", hrefLabel: "Enter an exam code" },
    ],
    next: ["trainee-certificate"],
  },
  {
    id: "trainee-assignment",
    audience: "trainee",
    title: "Do an assignment",
    question: "How do I do and submit an assignment?",
    summary: "Assignments are written work with no timer. Your answers save as you type, and you submit when you are ready.",
    keywords: ["assignment", "assignments", "homework", "submit assignment", "answer", "written", "feedback", "resubmit", "resubmission", "autosave", "graded"],
    steps: [
      { title: "Open Assignments", text: "In the menu choose **Assignments**. Each card shows its course, due date and status.", href: "/trainee/assignments", hrefLabel: "Open Assignments" },
      { title: "Read the questions", text: "Open an assignment and read the instructions. Pick a question from the list on the left." },
      { title: "Write your answer", text: "Type in the answer box. It saves by itself a couple of seconds after you stop; a small note under the box shows **Saving...** and then when it was saved.", tip: "Pasting into the box is turned off, so type your answer in your own words." },
      { title: "Move between questions", text: "Use **Previous** and **Next Question**. A tick on the left shows an answered question." },
      { title: "Submit", text: "On the last question press **Submit Assignment**, then confirm with **Submit**. Check the due date first.", tip: "After submitting you usually cannot change answers unless your instructor asks for a resubmission." },
      { title: "See your feedback", text: "When it has been assessed, open it from the list to see your score, feedback, **Strengths:** and **Focus on:**. If you see **Resubmission Needed**, open it and fix the questions marked for it." },
    ],
  },
  {
    id: "trainee-certificate",
    audience: "trainee",
    title: "Share and verify a certificate",
    question: "How do I share or print my certificate?",
    summary: "Every certificate has its own public page that anyone can open to confirm it is genuine.",
    keywords: ["certificate", "share certificate", "print certificate", "download certificate", "pdf", "verify certificate", "code", "linkedin", "employer check"],
    steps: [
      { title: "Open your certificates", text: "In the menu choose **Certificates** and press **View & verify** on the one you want.", href: "/trainee/certificates", hrefLabel: "Open Certificates" },
      { title: "Print or save a PDF", text: "On the certificate page press **Print / Save as PDF**." },
      { title: "Share it", text: "Copy the page address and send it. Anyone with the link can check it is genuine without logging in." },
      { title: "Let others verify a code", text: "Anyone can also type a certificate code under **Verify a Certificate** and press **Verify**.", href: "/certificate", hrefLabel: "Open verification" },
    ],
  },
  {
    id: "trainee-profile",
    audience: "trainee",
    title: "Set up your profile and choose who sees it",
    question: "How do I set up my profile and choose who can see it?",
    summary: "Your profile helps employers and organizations find you. You decide who can see it, and nothing is public unless you choose it.",
    keywords: ["profile", "visibility", "public", "private", "who can see", "username", "skills", "cv", "resume", "portfolio", "discoverability", "trainees page", "listed", "show me"],
    steps: [
      { title: "Open your profile", text: "Press your name card at the top of the menu to open your profile.", href: "/trainee/profile", hrefLabel: "Open Profile" },
      { title: "Fill in the basics", text: "Under **Basic Info** set your **Username**, **Location** and links, then press **Save**. Add **Skills**, **Education**, **Work Experience** and **Projects** below.", tip: "Your profile picture is changed from Settings." },
      { title: "Choose who sees it", text: "In **Profile Visibility** pick one: **Public — anyone, no sign-in required**, **Any signed-in AAICBI account**, **Approved employers only**, or **Private — only you and admins**. Then press **Save**.", tip: "To appear on the public Trainees page you need a username, a verified email and Public visibility." },
      { title: "Employer discoverability", text: "In **Settings**, under **Your visibility**, **Employer Discoverability** lets vetted employers find you. Your contact details stay hidden until you accept an introduction.", href: "/trainee/settings", hrefLabel: "Open Settings" },
      { title: "Share a link", text: "In **Settings**, **Generate Link** under **Public Profile Link** makes a link for your CV or LinkedIn. It works only while discoverability is on." },
    ],
    next: ["trainee-jobs"],
  },
  {
    id: "trainee-jobs",
    audience: "trainee",
    title: "Apply for jobs and answer introductions",
    question: "How do I apply for a job or answer an employer?",
    summary: "The Job Board and introductions work once employer discoverability is on. Your contact details are only shared when you choose.",
    keywords: ["job", "jobs", "apply", "job board", "employer", "introduction", "introductions", "opportunity", "hire", "career", "work"],
    steps: [
      { title: "Turn on discoverability", text: "The Job Board asks you to turn on discoverability in your settings first. Open **Settings** and switch on **Employer Discoverability**.", href: "/trainee/settings", hrefLabel: "Open Settings" },
      { title: "Open the Job Board", text: "From the dashboard open **Quick Actions**, press **Show more**, then choose **Job Board**.", href: "/trainee/job-postings", hrefLabel: "Open Job Board" },
      { title: "Apply", text: "Press **Apply** on a posting. Choose whether to tick **Share my contact information** and which **Certificates to share**, then press **Submit Application**." },
      { title: "Answer introductions", text: "When an employer is interested, open **Introductions**. Press **Review**, then **Accept** or **Decline**. Nothing is shared until you accept.", href: "/trainee/introductions", hrefLabel: "Open Introductions" },
    ],
  },
  {
    id: "trainee-help",
    audience: "trainee",
    title: "Message your cohort or get help",
    question: "How do I message my instructor or get help?",
    summary: "There are a few ways to ask for help, depending on what you need.",
    keywords: ["message", "messages", "chat", "help", "support", "instructor", "question", "contact", "admin", "report", "block"],
    steps: [
      { title: "Chat with others", text: "Open **Messages**, press **New chat**, and pick someone from the list. Staff are tagged **Staff** and employers **Employer**. Type in **Write a message…** and press **Send**.", href: "/trainee/messages", hrefLabel: "Open Messages", tip: "Employers appear in the list once you accept their introduction or apply to their job." },
      { title: "Ask about a lesson", text: "Use **Q&A** on the lesson in your course to ask a question your instructor and others can see." },
      { title: "Contact the platform team", text: "In **Settings**, under **Support**, fill in **Subject** and your message and press **Send message**.", href: "/trainee/settings", hrefLabel: "Open Settings" },
      { title: "Ask Loop about your progress", text: "**Ask Loop** in the menu is your learning buddy for questions about your own progress. Turn on **AI Study Buddy** in Settings first.", href: "/trainee/buddy", hrefLabel: "Open Ask Loop" },
    ],
  },
  {
    id: "trainee-settings",
    audience: "trainee",
    title: "Change your settings",
    question: "How do I change my settings and notifications?",
    summary: "Settings holds your picture, notifications, language and display options.",
    keywords: ["settings", "notifications", "whatsapp", "language", "dark mode", "low bandwidth", "data saver", "picture", "avatar", "password", "forgot password", "preferences"],
    steps: [
      { title: "Open Settings", text: "In the menu choose **Settings**.", href: "/trainee/settings", hrefLabel: "Open Settings" },
      { title: "Profile picture", text: "Under **Your account**, upload your **Profile Picture**." },
      { title: "Notifications", text: "Under **Notifications**, turn **Progress notifications** on or off, or enter your **WhatsApp phone number** and press **Enable WhatsApp Notifications** to get a code to verify it." },
      { title: "Language and display", text: "Under **Preferences**, choose your **Language**, switch on **Low-bandwidth mode** to save data, or **Dark Mode**." },
      { title: "Forgotten password", text: "There is no password box in Settings. If you forget your password, press **Forgot your password?** on the sign-in page and we email you a link.", href: "/trainee/forgot-password", hrefLabel: "Reset my password" },
    ],
  },
  {
    id: "trainee-explore",
    audience: "trainee",
    title: "Explore jobs, organizations and videos",
    question: "How do I explore the ecosystem and see job listings?",
    summary: "Explore is your way into the rest of the ecosystem from inside your own area: jobs, organizations, videos and events.",
    keywords: ["explore", "ecosystem", "job listings", "jobs", "organizations", "training organizations", "other organizations", "videos", "events", "browse", "discover", "see jobs"],
    steps: [
      { title: "Open Explore", text: "In the menu choose **Explore**.", href: "/trainee/explore", hrefLabel: "Open Explore" },
      { title: "See jobs", text: "Press **Jobs and opportunities** to see every open role. You can read them all; you need to be signed in to apply, and you choose what to share." },
      { title: "Look at organizations", text: "Press **Training organizations** to look at other organizations and follow the ones you like." },
      { title: "Watch and attend", text: "**Trainee videos** shows what other trainees built and learned, and **Events** lists open days and workshops." },
      { title: "Share your own", text: "**Share a video** takes you to My Videos. **Report a concern** is for telling the Super Admin about a problem.", tip: "A tile is missing if the platform has switched that part off." },
    ],
    next: ["trainee-video", "trainee-report"],
  },
  {
    id: "trainee-video",
    audience: "trainee",
    title: "Post a video for your organization to review",
    question: "How do I post my video and send it to my training organization?",
    summary: "You post a YouTube video, your training organization reviews it, and if there is a problem you can send it to AAICBI yourself.",
    keywords: ["post video", "share video", "upload video", "my videos", "youtube", "send video", "organization review", "super admin", "escalate", "declined", "withdraw", "showcase video"],
    steps: [
      { title: "Open My Videos", text: "In the menu choose **My Videos**.", href: "/trainee/videos", hrefLabel: "Open My Videos", tip: "You need to be enrolled in a course from a training organization to post to it." },
      { title: "Fill in the video", text: "Choose your **Training organization**, give the **Video title**, paste the **YouTube link**, and add a **Description** and **Skills**." },
      { title: "Choose where it goes", text: "Under **Send it to**, keep **My training organization** for the normal route. Choose **AAICBI (Super Admin) directly** if you cannot reach them or have had trouble." },
      { title: "Send it", text: "Press **Send for review** (or **Send to AAICBI** for the direct route). Your organization is told and decides." },
      { title: "Follow it", text: "Under **Your videos** you can see whether it is **Waiting for your organization**, **With AAICBI for review** or **Published**. If your organization gave a reason, it is shown there." },
      { title: "If there is a problem", text: "If your organization has not replied, or declined, press **Send to AAICBI for review**, say what the problem is, and press **Send to AAICBI**. You can also press **Withdraw** to take the video back before it is approved." },
    ],
    next: ["trainee-report"],
  },
  {
    id: "trainee-report",
    audience: "trainee",
    title: "Report a concern about an organization",
    question: "How do I report an abusive training organization?",
    summary: "You can tell the Super Admin, in confidence, if a training organization mistreated you. The organization is never told who sent the report.",
    keywords: ["report", "abuse", "abused", "harassment", "bullying", "complaint", "complain", "unfair", "mistreated", "fraud", "safety", "concern", "misconduct"],
    steps: [
      { title: "Open Report a Concern", text: "In the menu choose **Report a Concern**.", href: "/trainee/report", hrefLabel: "Open Report a Concern", tip: "You can report an organization whose course you are enrolled in." },
      { title: "Say who and what", text: "Choose the **Organization** and pick the closest match under **What happened?**." },
      { title: "Describe it", text: "In **Tell us what happened** write who, when and what, in at least 20 characters. Do not include passwords or card numbers." },
      { title: "Send it", text: "Press **Send report**. Only the Super Admin sees it, and the organization is not told who reported it." },
      { title: "Follow up", text: "Your report appears under **Your reports** with its status, and you get a notification when it has been looked at.", tip: "If you are in danger, contact your local emergency services first." },
    ],
  },
];
