import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/session";
import { withApiErrors } from "@/lib/apiError";

/**
 * GET /api/trainee/assignment-insights — the trainee's own cross-
 * assignment AI learning insight (§20), regenerated by
 * regenerateLearningInsight() after each AI-graded submission. Returns
 * null when none exists yet (no AI-graded submission, or generation
 * failed) rather than a 404 — "nothing to show yet" is a normal state,
 * not an error.
 */
export async function GET(_req: NextRequest) {
  return withApiErrors(async () => {
    const session = await requireRole("TRAINEE");
    const insight = await prisma.assignmentLearningInsight.findUnique({
      where: { traineeId: session.userId },
      select: { strengths: true, weaknesses: true, narrative: true, generatedAt: true },
    });
    return NextResponse.json({ insight });
  });
}
